/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package perfume.bot;

import org.junit.Test;
import static org.junit.Assert.*;

public class MindTest {
    @Test public void testMind() {
        Mind classUnderTest = new Mind();
        assertNotNull("", "");
    }
}
